export const ROUTES = Object.freeze({
    HOME: "/",
    LOGIN: "/login",
    CUSTOMER_BILL: "/showBill/:customerBillId",
    ADD_EXPIRED_ITEM: "/addExpiredItem",
    EXPIRED_ITEM_LIST: "/expiredItemList",
    BILLING: "/billing",
    OPEN_CLOSE: "/openClose",
    INVENTORY: "/inventory",
    INVENTORY_ITEMS_BY_ID: "/inventory/:id",
    PURCHASE_ORDER_ITEMS_BY_ID: "/purchaseorder/:id",
    DAY_BILL: "/dayBill",
    ATTENDANCE: "/attendance",
    STOCK_QUANTITY: "/stockquantity",
    ALL_BILL: "/allBill",
    PURCHASE_ORDER: "/purchase",
    PURCHASE_ORDER_BY_ID: "/purchase/:id",
    REPORT: "/report",
    APPROVAL: "/approval",
    EXPIRED_ITEMS: "/expiredItems",
    LABEL: "/label",
    ORDERS: "/orders",
    ORDER_BY_STATUS: "/orders/:orderStatus",
    NEW_BILLING: "/newBilling",
    ITEMS_BARCODE: "/itemsBarcode",
    MOVE_TO_CART: "/moveToCart",
    PAID_PO: "/paidPOs",
    UNPAID_PO: "/unpaidPOs",
    PURCHASE_ORDER_BILL_BY_ID: "/purchaseOrderBill/:id",
    RETURN_AND_EXCHANGE: "/returnAndExchange",
    PO_SELL_DETAILS: "/sellDetailsPage/:purchaseOrderId",
    BARCODE_PRINT: "/barcodePrint",
    NEW_PURCHASE_ORDER: "/new-purchase-order",
    NEW_PURCHASE_ORDER_BY_ID: "/new-purchase-order/:id",
    STORE_INVENTORY_MANAGEMENT: "/createTransaction",
    STORE_INVENTORY: "/storeInventory",
    STORE_TRANSACTIONS:"/stockTransactions",
    NEW_INVENTORY_PAGE: "/newInventoryPage",
    ITEM_PURCHASE_ORDERS:"/item-purchase-orders",
    STORE_INVENTORY_MANAGEMENT_BY_ID: "/createTransaction/:id",
    EXPIRY_ITEMS_BATCH: "/expiry-items-batch",
    EXPIRY_ITEMS_BATCH_BY_ID: "/expiry-items-batch/:id",
})