[build]
  # This will be run the site build
  command = "npm run build"
  # This is the directory is publishing to netlify's CDN
  publish = "build"
  # functions build directory
  functions = "functions-build"
[dev]
    command = "npm run server"
    framework = "#custom"
    targetPort = 9000


[context.production.environment]
  ENV_NAME = "production"
  NODE_ENV = "production"
  PROD_DB = "mongodb+srv://JeXcBPk752QAfjCb:JeXcBPk752QAfjCb@cluster0.k468m.mongodb.net/pstores-prod?retryWrites=true&w=majority"