export const routes = {
  home: '/',
  login: '/login',
  showBill: '/showBill/:customerBillId',
  billing: '/billing',
  openClose: '/openClose',
  inventory: '/inventory',
  dayBill: '/dayBill',
  stockQuantity: '/stockquantity',
  allBills: '/allBill',
  billReport: '/report',
  editBill: '/edit/:billingID',
  approval: '/approval',
  editPurchaseOrder: '/',
  orders:'/orders',
  orderStatusDetail: '/orders/:orderStatus',
  itemsBarcode: "/itemsBarcode",
  moveToCart:"./moveToCart",
  paidPOs:"./paidPOs",
  unpaidPOs:"./unpaidPOs",
  unpaidPurchaseOrder:"./unpaidPurchaseOrder",
  payPurchaseOrderBill:"/payPurchaseOrderBill",
  addExpiredItem:'/addExpiredItem',
  storeInventory:'/storeInventory',
};
