export const CONSTANTS = Object.freeze({
    REJECT: "reject",
    APPROVE: "approve",
    DRAFT: "draft",
    CREDIT: "credit",
    PAYMENT: "payment",
    PARTIALLY_PAID: "partially paid",
    FULLY_PAID: "fully paid",
    NEFT: "neft",
    UPI: "upi",
    CASH: "cash",
    PREPAID: "prepaid",
    YES: "Yes",
    NO: "No",
    NO_IMAGE_AVAILABLE:'No Image Available',
    NO_PAYMENTS_AVAILABLE:'No Payments Available',
    NO_CREDITS_AVAILABLE:'No Credits Available',
})