export const TransactionTableConstants = Object.freeze({
    TRANSACTIONID:"transactionId",
    COLUMNS: [
      { key: 'transactionId', label: 'Transaction ID' ,flex: 0,
        minWidth: 250,},
      { key: 'itemName', label: 'Item Name' },
      { key: 'price', label: 'Price' },
      { key: 'qty', label: 'Source Qty' },
      { key: 'sourceExpiry', label: 'Source Expiry' },
      { key: 'sourceMfg', label: 'Source Mfg' },
      { key: 'destinationQty', label: 'Destination Qty' },
      { key: 'destinationExpiry', label: 'Destination Expiry' },
      { key: 'destinationMfg', label: 'Destination Mfg' },
      { key: 'ItemSourceRemark', label: 'Item Source Remark' },
      { key: 'ItemDestinationRemark', label: 'Item Destination Remark' },
      { key: 'itemError', label: 'Error Info' },
      { key: 'dateOfTransaction', label: 'Transaction Date' },
      { key: 'transactionType', label: 'Transaction Type' },
      { key: 'sourceType', label: 'Source Type' },
      { key: 'sourceRemark', label: 'Source Remark' },
      { key: 'sourceStaff', label: 'Source Staff' },
      { key: 'destinationType', label: 'Destination Type' },
      { key: 'destinationRemark', label: 'Destination Remark' },
      { key: 'destinationStaff', label: 'Destination Staff' },
      { key: 'transactionReason', label: 'Transaction Reason' },
      { key: 'transactionStatus', label: 'Status' },
      { key: 'hasErrors', label: 'Has Errors' },
      { key: 'approvedByAdmin', label: 'Approved By Admin' },
      { key: 'adminRemark', label: 'Admin Remark' },
      {key: 'edit', label: 'Edit' },
    ],
  });
  