export const getPurchasedItemByItem = (item: any) => ({
  item_id: item._id,
  barcode: item.itemBarcode,
  inputName: item.itemName,
  mrp: item.itemMRPperUnit,
  costPrice: item.itemCostPricePerUnit,
  sellingPrice: item.itemSellingPricePerUnit,
  brand: item.itemBrandName,
  category: item.itemCategory,
  unit: item.quantityUnitName,
  itemQuantity: item.itemPerUnitQuantity,
  companyName: item.companyName,
  subCategory: item.subCategory,
  flavourOrFeature: item.flavourOrFeature,
  shelfLife: item.shelfLife,
  saleTime: item.saleTime,
  returnPolicyAvailable: item.returnPolicyAvailable,
  returnPolicyRemarks: item.returnPolicyRemarks,
  freeItemsAvailable: item.freeItemsAvailable,
});
